### ISSUE TITLE
Incorrect leaps version

### ISSUE THREAD

**Issue by Enchufa2** [WLenhard/cNORM#1] opened 2019-08-27 12:06 UTC
Should be 3.0 instead of 3.0.0. This doesn't matter on CRAN, because in R package_version("3.0") == package_version("3.0.0"), but I found it causes issues in other systems (e.g., RPM packaging).

**Comment by WLenhard** [comment] 2019-08-27 17:36
Thank you very much. I wasn't aware of that. The issue is fixed in the code and it will be incorporated in the next official release to CRAN.

**Closed as completed** 2019-08-31 19:43 UTC
